##
## Test Suites
##

    modified.files.includes[relevant][site-navigation-language-web-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    modified.files.includes[relevant][site-navigation-language-web-playwright-rule]=**

    relevant.rule.names=\
        site-navigation-language-web-java-rule,\
        site-navigation-language-web-playwright-rule

    test.batch.names[relevant][site-navigation-language-web-java-rule]=\
        modules-integration-mysql57,\
        modules-unit

    test.batch.names[relevant][site-navigation-language-web-playwright-rule]=\
        playwright-js-tomcat90-mysql57

][relevant][site-navigation-language-rule]=site-navigation-language-web

##
## Testray
##

    testray.main.component.name=Language Widget