dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "org.apache.ant", name: "ant", transitive: false, version: "1.10.14"
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":apps:portal:portal-verify-test-util")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}

tasks.named('testIntegration', Test) {
	doFirst {
		def hostName = System.getenv('HOSTNAME')

		println "host name is ... ${hostName}"

		if (hostName != null && !hostName.isEmpty()) {
			def envSpecificPropsFileName = "test.${hostName}.properties"
			def testPropsFileName = "test.properties"

			println "Root dir : ${rootDir.absolutePath}"

			def propsFile = new File(rootDir.ParentFile, envSpecificPropsFileName)

			println "root dir parent file props file : ${propsFile.absolutePath}"
			 
			if (propsFile.exists()) {
				println "Loading environment-specific properties from: ${propsFile.absolutePath}"
				def loadedProperties = new Properties()

				propsFile.withInputStream {
					loadedProperties.load(it)
				}

				loadedProperties.each {
					key, value ->
					systemProperty key, value 
					println "  - Set JVM system property: ${key}=${value}"
				}
			} else {
				println "Warning: Environment-specific properties file not found: ${envSpecificPropsFileName} rootDir"
			}
		} else {
			println "Warning: HOST_NAME environment variable not set. Skipping environment-specific properties loading."
		}
	}
}