##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant][blogs-web-rule]=blogs-web

    test.batch.run.property.query[functional-tomcat90-mysql57-jdk8][relevant][blogs-web-rule]=\
        (testray.component.names == "Blogs") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    test.batch.names[relevent][blogs-web-rule]=\
        functional-tomcat90-mysql57-jdk8

    relevant.rule.names=\
        blogs-web-rule

    modified.files.includes[relevant][blogs-web-rule]=*

##
## Testray
##

    testray.main.component.name=Blogs